### ISSUE TITLE
Import button on message decrypting

### ISSUE THREAD

**Issue by TheLastProject** [keys-pub/app#12]
When decrypting a message under Tools, the key is displayed. However, to actually be able to reply, one needs to manually copy the key, then go to Keys, click Import and paste the key there. It would be really convenient if the green text box stating "Verified longkeyidhere" would also have an Import button next to it if they key wasn't already imported, so responding would be much easier.

I'm willing to take on this issue myself if agreed that this would be an improvement.

**Comment by gabriel** [comment]
Yeah some option(s) there would be nice... I'm thinking there could be an option to lookup the key and verify it before importing... maybe a "Lookup" or "Search" button (instead of "Import"?) that shows any verified info in a dialog (with the option to import). Similar to how search shows the key before giving the option to import.

I'm open to other ideas here too.

**Comment by TheLastProject** [comment]
I think for metadata privacy reasons we should make it easy to import the key without an online search too.

What about:
- Import button only
- Pressing it will ask if you want to import the key with a line saying "user: unknown" and a "look up online" button next to it, with the yes/no being below that

I think that may strike the right balance between easy import and lookup while not leaking metadata too easily to the server who you got a message from?

**Comment by gabriel** [comment]
I added a "Lookup" button on decrypt and verify that allows you to search for a key and import if you don't have it saved.

![2020-08-10 at 11 47 AM](https://user-images.githubusercontent.com/2669/89818895-60934000-daff-11ea-83f4-0694a8b580b8.png)
